site_name: CANARI-ML
theme:
  name: material
  highlightjs: false
  color_mode: dark
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: darkly
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Red Hat Mono
  logo: assets/images/canari-hero-image.png
  favicon: assets/images/canari-hero-image.png
  icon:
    annotation: material/arrow-right-circle-outline
  features:
    - optimize
    - content.code.copy
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch # Will start to fetch a page once the user hovers over a link
    - navigation.tracking
    # - navigation.expand
    - navigation.path
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.code.annotate

# copyright: MIT License; 2025 British Antarctic Survey
copyright: <a href="https://github.com/CANARI-ML/canari-ml/blob/main/LICENSE">MIT License</a> | 2025 | British Antarctic Survey
extra:
  generator: false
  social:
    - icon: fontawesome/solid/globe
      link: https://www.bas.ac.uk/project/canari/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bryn-noel-ubald/
    - icon: simple/github
      link: https://github.com/canari-ml/canari-ml/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/brynnoelubald.bsky.social

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_if_no_docstring: true
            show_inheritance_diagram: true    # Show inheritance diagram for classes
            show_signature: true  # Show function signatures (args, return type)
            show_source: true # Show source code for functions and classes
            show_root_full_path: true # Show full path of root path in headings
            show_object_full_path: true    # Show full path of objects in signatures
            # heading_level: 2   # Heading level for members (1 to 6)
            members_order: source   # Order of members in the documentation
            filters: ["!^_"]   # Exclude patterns from members
            merge_init_into_class: true    # Merge __init__ methods into class docstrings
            show_root_heading: true    # Show the root heading in the documentation
            allow_inspection: true     # Allow inspecting modules (importing them) when it is not possible to visit them (parse their source code)
            show_bases: true     # Show base classes in the documentation
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - privacy
  - autorefs

extra_css:
  - css/github-permalink-style.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=permalink#table-of-contents
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - Getting started:
    - Installation: installation.md
  - Usage:
    - Download data: download.md
    - Preprocess data: preprocess.md
    - Train: train.md
    - Predict: predict.md
    - Postprocess: postprocess.md
    - Plot: plot.md
  - Scripted Usage:
    - Experiments: running_experiments.md
  - Code Reference: reference/
