site_name: CANARI-ML
repo_url: https://github.com/canari-ml/canari-ml/
repo_name: canari-ml
site_author: Bryn Noel Ubald
theme:
  name: material
  highlightjs: false
  color_mode: dark
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: darkly
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Red Hat Mono
  logo: assets/images/canari-hero-image.png
  favicon: assets/images/canari-hero-image.png
  icon:
    annotation: material/arrow-right-circle-outline
  features:
    - content.code.annotate
    - content.code.copy
    # - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    - optimize

copyright: <a target="_blank" rel="noopener noreferrer" href="https://github.com/CANARI-ML/canari-ml/blob/main/LICENSE">MIT License</a> | 2025 | <a target="_blank" rel="noopener noreferrer" href="https://www.bas.ac.uk/">British Antarctic Survey</a>
extra:
  generator: false
  social:
    - icon: fontawesome/solid/globe
      link: https://www.bas.ac.uk/project/canari/
    - icon: simple/github
      link: https://github.com/canari-ml/canari-ml/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bryn-noel-ubald/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/brynnoelubald.bsky.social

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_if_no_docstring: true
            show_inheritance_diagram: true    # Show inheritance diagram for classes
            show_signature: true  # Show function signatures (args, return type)
            show_source: true # Show source code for functions and classes
            show_root_full_path: true # Show full path of root path in headings
            show_object_full_path: true    # Show full path of objects in signatures
            # heading_level: 2   # Heading level for members (1 to 6)
            members_order: source   # Order of members in the documentation
            filters: ["!^_"]   # Exclude patterns from members
            merge_init_into_class: true    # Merge __init__ methods into class docstrings
            show_root_heading: true    # Show the root heading in the documentation
            allow_inspection: true     # Allow inspecting modules (importing them) when it is not possible to visit them (parse their source code)
            show_bases: true     # Show base classes in the documentation
  - gen-files:
      scripts:
        # - docs/gen_help.py
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - toggle-sidebar:
      toggle_button: all
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      theme:
        light: material/indigo-light
        dark: material/indigo-dark
      cache:
        backend: local
        local:
          path: "~/.cache/mkdocs_puml"
      interaction:
        enabled: true
  - markdown-exec
  - git-revision-date-localized
  - section-index
  - privacy
  - autorefs

extra_css:
  - css/github-permalink-style.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=permalink#table-of-contents
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - Getting started:
    - Installation: user-guide/getting-started/installation.md
    - Hydra usage: user-guide/getting-started/hydra.md
    - CLI help: help/general.md
    - Software architecture: user-guide/getting-started/software_architecture.md
  - Main Usage:
    - user-guide/index.md
    - Download data:
      - user-guide/download/index.md
      - CLI usage: user-guide/download/cli_usage.md
      - Config file usage: user-guide/download/config_file_usage.md
      - Output structure: user-guide/download/output_structure.md
      - CLI help: help/download.md
    - Preprocess data:
      - user-guide/preprocess/index.md
      - CLI usage: user-guide/preprocess/cli_usage.md
      - Config file usage: user-guide/preprocess/config_file_usage.md
      - Output structure: user-guide/preprocess/output_structure.md
      - CLI help: help/preprocess.md
    - Train:
      - user-guide/train/index.md
      - CLI usage: user-guide/train/cli_usage.md
      - Config file usage: user-guide/train/config_file_usage.md
      - Advanced usage: user-guide/train/advanced_usage.md
      # - Help: user-guide/train/help.md
      - CLI help: help/train.md
    - Predict:
      - user-guide/predict/index.md
      - Config file usage: user-guide/predict/config_file_usage.md
      - CLI help: help/predict.md
    - Postprocess:
      - user-guide/postprocess/index.md
      - CLI help: help/postprocess.md
    - Plot:
      - user-guide/plot/index.md
      - CLI help: help/plot.md
    - "Advanced: SLURM Submission":
      - user-guide/slurm.md
  # - Examples:
  #   - Experiments: user-guide/experiments/index.md
  - Code Reference: reference/
