# @package _global_

defaults:
  - /paths/download    # Used to get path to source downloaded data config file
  - /paths/postprocess # Used to get path to output postprocessed data to & pred output
  - /paths/plot # Used to get path to output plots to
  - _self_
