# @package _global_

defaults:
  - _self_
  - /paths/train
  - /common/default
  - /model/default                  # This can be changed to any of the models in conf/model/
  - /callbacks/default              # This can be changed to any of the callbacks in conf/callbacks/
  - /logger/tensorboard             # This can be changed to any of the loggers in conf/logger/
  - /trainer/default                # This can be changed to any of the trainers in conf/trainer/
  - /hydra_config/train             # Used to set output path for training

train:
  dataset: ???
  name: ???
  seed: 42
  epochs: 50
  workers: 4
  batch_size: 4
  shuffling: true
  wandb_group: unet
  wandb_project: CANARI

verbose: true
