defaults:
    - paths.yaml
    - download.yaml
    - preprocess.yaml
    - _self_

inputs:
    forecast_length: 3
    lag_length: ${inputs.forecast_length}
    train_start: 2000-1-5
    train_end: 2000-1-5
    val_start: 2000-4-5
    val_end: 2000-4-5
    test_start: 2000-2-1
    test_end: 2000-2-1
    absolute_vars: ua700
    anomaly_vars: ""

# hydra:
#   run:
#     dir: outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
