defaults:
    - download.yaml
    - preprocess.yaml
    - _self_

inputs:
    forecast_length: 3
    lag_length: ${inputs.forecast_length}
    train_start: 2018-1-4|2019-1-4
    train_end: 2018-1-4|2019-1-4
    val_start: 2019-4-5
    val_end: 2019-4-5
    test_start: 2024-12-1
    test_end: 2024-12-1
    absolute_vars: ua700
    anomaly_vars: ""
