defaults:
  - _self_
  - model: default
  - callbacks: default
  - logger: tensorboard
  - trainer: default
  - override hydra/job_logging: colorlog_custom
  - override hydra/hydra_logging: colorlog

hydra:
  job:
    name: train
  run:
    dir: outputs/${train.run_name}/training/
  sweep:
    dir: outputs/${train.run_name}/training_ensemble/
    subdir: ${train.seed}

train:
  dataset: ???
  run_name: ???
  seed: 42
  max_epochs: 50
  workers: 4
  batch_size: 4
  shuffling: true
  verbose: true
