# Boiler plate - not to be modified unless specified
# __________________________________________________

defaults:
  - train: default
  - _self_
  - override hydra/launcher: basic
  - override hydra/job_logging: colorlog_custom
  - override hydra/hydra_logging: colorlog

hydra:
  job:
    name: train
  # # Allow experiment file defs to work from current run path, and not Python config-path definition
  # searchpath:
  #   - file://.
